query {
    dagger {
        engine {
            zenith {
                cli(workerRegistry: "jeremyatdockerhub/dagger-engine-worker-zenith", arch: "amd64", operatingSystem: "linux") {
                    export(path: "./dist/dagger-zenith-linux-amd64")
                }
                worker {
                    publish(ref: "jeremyatdockerhub/dagger-engine-worker-zenith:main")
                }
            }
        }
    }
}
