query {
    dagger {
        engine {
            fromZenithBranch {
                cli(workerRegistry: "jeremyatdockerhub/dagger-engine-worker-zenith", arch: "arm64", operatingSystem: "darwin") {
                    export(path: "./dist/dagger-zenith-darwin-arm64")
                }
                worker {
                    publish(ref: "jeremyatdockerhub/dagger-engine-worker-zenith:main")
                }
            }
        }
    }
}
