name: Nightly Zenith build

on:
  #schedule:
  #  - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  nightly:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "${{ secrets.DHTOKEN }}" | docker login -u jeremyatdockerhub --password-stdin
      - run: cd /usr/local/bin && { sudo curl -L https://github.com/jpadams/shykes-dagger-zenith-builder/releases/download/nightly/dagger-zenith-linux-amd64 -o dagger; sudo chmod +x dagger; cd -; }
      # Fail if this binary doesn't work
      - run: dagger version
        shell: bash

#      - run: |
#          docker run \
#            --name dagger-engine \
#            --privileged \
#            --stop-signal SIGTERM \
#            -d \
#            -v dagger-engine:/var/lib/dagger \
#            jeremyatdockerhub/dagger-engine-worker-zenith:main
#
#      - run: docker ps
#        shell: bash
#        
      - run: |
#          dagger query -m github.com/shykes/daggerverse/dagger --doc ./graphql/publish-zenith-linux-amd64.gql
#          dagger query -m github.com/shykes/daggerverse/dagger --doc ./graphql/publish-zenith-linux-arm64.gql
#          dagger query -m github.com/shykes/daggerverse/dagger --doc ./graphql/publish-zenith-darwin-amd64.gql
          dagger query -m github.com/shykes/daggerverse/dagger --doc ./graphql/publish-zenith-darwin-arm64.gql
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
#          _EXPERIMENTAL_DAGGER_RUNNER_HOST: docker-container://dagger-engine
#          _EXPERIMENTAL_DAGGER_CLI_BIN: /usr/local/bin/dagger
#
#      # Fail if this built binary doesn't work
#      - run: ./dist/dagger-zenith-linux-amd64 version
#        shell: bash
#      #- run: echo "{helloWorld{message withName(name: \"Monde\"){withGreeting(greeting: \"Bonjour\"){message}}}}" | ./dist/dagger-zenith-linux-amd64 query -m github.com/shykes/daggerverse/helloWorld
#
      - run: |
#          gh release delete nightly --yes
#          gh release create nightly --prerelease --notes-from-tag
#          gh release upload --clobber nightly ./dist/dagger-zenith-linux-amd64
#          gh release upload --clobber nightly ./dist/dagger-zenith-linux-arm64
          gh release upload --clobber nightly ./dist/dagger-zenith-darwin-amd64
#          gh release upload --clobber nightly ./dist/dagger-zenith-darwin-arm64
        env:
          GH_TOKEN: ${{ secrets.GHTOKEN }}
#
#      - name: Stop Engine
#        run: |
#          docker stop -t 300 dagger-engine
#          docker logs dagger-engine
