name: Nightly Zenith build

on:
  #schedule:
  #  - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  nightly:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "${{ secrets.DHTOKEN }}" | docker login -u jeremyatdockerhub --password-stdin
      - run: cd /usr/local/bin && { sudo curl -L https://github.com/jpadams/shykes-dagger-zenith-builder/releases/download/nightly/dagger-zenith-linux-amd64 -o dagger; sudo chmod +x dagger; cd -; }
      # Fail if this binary doesn't work
      - run: dagger version
        shell: bash

      - run: |
          dagger query -m github.com/kpenfound/zenith-releaser/dagger --doc ./graphql/publish-zenith-linux-amd64.gql # this one builds worker image and cli
          dagger query -m github.com/kpenfound/zenith-releaser/dagger --doc ./graphql/publish-zenith-linux-arm64.gql # these just build clis
          dagger query -m github.com/kpenfound/zenith-releaser/dagger --doc ./graphql/publish-zenith-darwin-amd64.gql
          dagger query -m github.com/kpenfound/zenith-releaser/dagger --doc ./graphql/publish-zenith-darwin-arm64.gql
        shell: bash
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      # Fail if this built binary doesn't work
      - run: ./dist/dagger-zenith-linux-amd64 version
        shell: bash

      - run: docker stop -t 300 $(docker ps --filter name="dagger-engine-*" -q)

      - run: |
          gh release upload --clobber nightly ./dist/dagger-zenith-linux-amd64
          gh release upload --clobber nightly ./dist/dagger-zenith-linux-arm64
          gh release upload --clobber nightly ./dist/dagger-zenith-darwin-amd64
          gh release upload --clobber nightly ./dist/dagger-zenith-darwin-arm64
        env:
          GH_TOKEN: ${{ secrets.GHTOKEN }}
